# Timeout in seconds that Limine will use before automatically booting.
timeout: 1

# The entry name that will be displayed in the boot menu.
/edos
    # We use the Limine boot protocol.
    protocol: limine
    resolution: 1920x1080

    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    kernel_path: boot():/boot/kernel
    cmdline: root=UUID=87654321-4321-8765-cba9-987654321fed rootfstype=fat32
