[package]
name = "efs-fsck"
version = "0.1.0"
edition = "2024"

[lib]
name = "efs_fsck"
path = "src/lib.rs"

[[bin]]
name = "efs-fsck"
path = "src/main.rs"

[dependencies]
efs-common = { path = "../../libs/efs-common" }

[lints.clippy]
unnecessary_safety_comment = "warn"
unnecessary_safety_doc = "warn"
allow_attributes_without_reason = "warn"
