[package]
name = "edos-kernel"
version = "0.1.0"
edition = "2024"

[features]
default = []
test = []

[dependencies]
limine = "0.5"
spin = "0.10.0"
x86_64 = "0.15.2"
uart_16550 = { version = "0.4.0", features = ["nightly"] }
x2apic = "0.5.0"
acpi = { version = "6.0.1" }
pc-keyboard = "0.8.0"
crossbeam-queue = { version = "0.3.12", default-features = false, features = [
    "alloc",
    "nightly",
] }
thiserror = { version = "2.0.16", default-features = false }
bytemuck = { version = "1.23.2", features = ["latest_stable_rust", "extern_crate_alloc", "nightly_portable_simd", "nightly_stdsimd", "nightly_docs"] }
pic8259 = "0.11.0"
elf = { version = "0.8.0", default-features = false, features = ["alloc"] }
raw-cpuid = "11.6.0"
lru = { version = "0.16.1", features = ["nightly"] }
heapless = "0.9.1"
buddy_system_allocator = "0.11.0"
bitflags = { version = "2.9.4", default-features = false, features = ["bytemuck"] }

[profile.dev]
opt-level = 2
