[package]
name = "elibc"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
documentation = "https://docs.rs/elibc"
authors = ["Edgar Luque <edgar@edgarluque.com>"]
description = "edos kernel libc"

[dependencies]
x86_64 = "0.15.2"
spin = "0.10.0"
linked_list_allocator = "0.10.5"
thiserror = { version = "2.0.9", default-features = false }
noto-sans-mono-bitmap = { version = "0.3.1", features = [
    "bold",
    "size_24",
    "size_32",
] }

[lib]
crate-type = ["rlib", "staticlib"]
