[workspace]
resolver = "3"
members = ["edos_lib", "edos_render", "edos-wm", "edos-taskbar", "edos-terminal", "edos-sh", "hello", "alloctest", "wintest", "echo", "cat", "ls", "stat", "free", "ps", "dmesg", "mkdir", "rmdir", "rm", "mv", "write", "grep", "head", "tail", "wc", "touch", "cp", "uname", "hexdump", "mount", "ping", "dns", "http", "df", "forktest", "sleep", "play", "edos-vi", "yes", "seq", "sort", "uniq", "tee", "tr", "env", "wget", "sync", "mmaptest", "evicttest", "lockordertest", "inflighttest", "true", "false", "kill", "basename", "dirname", "cut", "cal", "find", "du", "diff", "xargs", "sha256sum", "file", "threadtest", "iotest", "tcptest", "exectest", "edos-init"]

[profile.dev]
opt-level = 3
